version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    container_name: custom-node-docker-jenkins-container
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
